const mongoose = require('mongoose');
const Schema = mongoose.Schema;
//comment 
//. = _ _ _ = 3 gạch
//_ = _ _ = 2 gạch
// __ = _ = 1 gạch
const oddsSchema = new Schema({
	match_id: String,
	odd_bookmakers: String,
	odd_date: String,
	odd_1: String,
	odd_x: String,
	odd_2: Date,
	odd_1x: String,
	odd_12 : String,
    odd_x2 : String,    
    ah_4___5_1: String,
	ah_4___5_2: String,
	ah_4_1: String,
	ah_4_2: String,
	ah_3___5_1: String,
	ah_3___5_2 : String,
    ah_3_1: String,
    ah_3_2: String,
	ah_2___5_1: String,
	ah_2___5_2: String,
	ah_2_1: String,
	ah_2_2: String,
	ah_1___5_1: Array,
	ah_1___5_2: Array,
    ah_1_1: Object,    
    ah_1_2: String,
	ah0_1: String,
	ah0_2: String,
	ah__0___5_1: String,
    ah__1_1: String,
    ah__1_2: String,
	ah__1___5_1: String,
	ah__1___5_2: String,
	ah__2_1: String,
	ah__2_2: String,
	ah__2___5_1: Array,
	ah__2___5_2: Array,
    ah__3_1: Object,    
    ah__3_2: String,
	ah__3___5_1: String,
	ah__3___5_2: String,
	ah__4_1: String,
    ah__4_2: String,
    ah__4___5_1: String,
	ah__4___5_2: String,
	o__0___5: String,
	u__0___5: String,
	o__1: String,
	u__1: Array,
	o__1___5: Array,
    u__1___5: Object,
    o__2: String,
    u__2: String,
	o__2___5: String,
	u__2___5: String,
	o__3: String,
    u__3: String,
    o__3___5: String,
	u__3___5: String,
	o__4: String,
	u__4: String,
	o__4___5: String,
	u__4___5: Array,
	o__5: Array,
    u__5: Object,
    o__5___5: String,
    u__5___5:String,
    bts_yes: String,
	bts_no: String
	
});

const odds = mongoose.model('Odds', oddsSchema, 'Odds');

module.exports = odds;
